name: Unit test CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout project
      uses: actions/checkout@v2
    - name: composer install
      uses: php-actions/composer@v1
    - name: phpUnitMan
      run: /vendor/bin/phpunit
    - name: phpUnitAuto
      uses: php-actions/phpunit@v1
